#!/usr/bin/perl
for ($i=0; $i <= 100; $i++) {
    $fzbz = 0;
    if($i % 3 == 0) {
        $fzbz = 1;
        print "Fizz"
    }
    if($i % 5 == 0) {
        $fzbz = 1;
        print "Buzz"
    }
    if(!$fzbz) {
        print $i;
    }
    print "\n";
}
